version: 2.1
jobs: 
  build: 
    docker:
      - image: cimg/python:3.9.4
    environment:
      START: 451
      END: 500
    steps: 
      - checkout # check out the code in the project directory
      - run: | 
          sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
          sudo chmod a+rx /usr/local/bin/youtube-dl 
          
      - run: | 
          sudo apt update 
          sudo apt install aria2 ffmpeg wireguard python3
      - run: |
          wget https://github.com/ipfs/go-ipfs/releases/download/v0.8.0/go-ipfs_v0.8.0_linux-amd64.tar.gz
          tar -xvzf 'go-ipfs_v0.8.0_linux-amd64.tar.gz'
      - run: |
          chmod +x ./go-ipfs/install.sh
          sudo ./go-ipfs/install.sh
      
      - run: |
          ipfs init

      - run: ipfs ls bafybeiaysi4s6lnjev27ln5icwm6tueaw2vdykrtjkwiphwekaywqhcjze
     # - run: | 
       #   mkdir vid
       #   cd vid
       #   youtube-dl -i --playlist-start=$START --playlist-end=$END --write-thumbnail --external-downloader=aria2c -f '[height=1080]/bestvideo+bestaudio/best' -- "${URL}"
      
   #   - run: 
     #     command: |
      #      ipfs pin remote service add nft-storage https://api.nft.storage ${NFT_API_KEY}
      #      for cid in $(ipfs add -Q --cid-version 1 -r ./vid); do ipfs pin remote add --service=nft-storage --name=mv_y_$START-$END --background $cid; done
      #    no_output_timeout: 1h
     
     # - run:
     #     command: ipfs daemon
     #     no_output_timeout: 3h
