# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Main CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    env:
      START: 21
      END: 40

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install youtube-dl
      run: |
        sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl 
        sudo chmod +x /usr/local/bin/youtube-dl
        
    - name: Install aria2c and ffmpeg
      run: |
        sudo apt install aria2 ffmpeg
        
    - run: |
        mkdir vid
        cd vid
        youtube-dl --playlist-start=$START --playlist-end=$END --write-thumbnail --external-downloader=aria2c -f '[height>=?1080]/bestvideo+bestaudio/best' -- '${{ secrets.URL }}'

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        # Artifact name
        name: mv_$START-$END
        # A file, directory or wildcard pattern that describes what to upload
        path: ./vid
